org.gradle.jvmargs=-Xmx16g -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
kotlin.daemon.jvmargs=-Xmx8g
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official

android.useAndroidX=true
android.nonTransitiveRClass=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
